import test from 'node:test';
import assert from 'node:assert/strict';
import {problems,emptySolution,compareReports,SubmissionValidator,RubricEvaluator,BrowserAttemptRepository,EvaluationService} from '../lib/practice.ts';
function repo(){const data=new Map();return new BrowserAttemptRepository({getItem:k=>data.get(k)??null,setItem:(k,v)=>{data.set(k,v);}});}
function attempt(){return {id:'test-1',problemId:problems[0].id,createdAt:new Date().toISOString(),solution:structuredClone(problems[0].example),status:'queued' as const};}
test('incomplete submissions are rejected with the missing section',()=>{assert.throws(()=>new SubmissionValidator().validate(emptySolution()),/classes & responsibilities/);});
test('all problem examples are valid submissions',()=>{for(const p of problems)assert.doesNotThrow(()=>new SubmissionValidator().validate(p.example));});
test('oversized input is rejected',()=>{assert.throws(()=>new SubmissionValidator().validate({...problems[0].example,flow:'a'.repeat(12001)}),/12,000/);});
test('report quotes submitted text and does not pretend to score correctness',()=>{const r=new RubricEvaluator().evaluate(problems[0],problems[0].example);assert.equal(r.mode,'heuristic');assert.ok(r.findings.length>10);assert.equal(r.nextSteps.length,3);assert.ok(Object.values(problems[0].example).some(text=>text.includes(r.findings[0].evidence)));assert.match(r.summary,/does not verify correctness/);});
test('repository updates a status without duplicating an attempt',()=>{const r=repo();const a=attempt();r.save(a);r.save({...a,status:'evaluating'});assert.equal(r.list().length,1);assert.equal(r.list()[0].status,'evaluating');});
test('evaluation completes and stores the report',()=>{const r=repo();const result=new EvaluationService(new RubricEvaluator(),r).run(attempt(),problems[0]);assert.equal(result.status,'completed');assert.ok(r.list()[0].report!.findings.length>10);});
test('evaluator failure preserves submission and can be retried',()=>{const r=repo();const service=new EvaluationService({evaluate(){throw new Error('Provider timeout');}},r);const a=attempt();const failed=service.run(a,problems[0]);assert.equal(failed.status,'failed');assert.deepEqual(failed.solution,a.solution);const retried=new EvaluationService(new RubricEvaluator(),r).run(failed,problems[0]);assert.equal(retried.status,'completed');assert.equal(r.list().length,1);});
test('revision does not overwrite parent snapshot',()=>{const r=repo();const a=attempt();r.save(a);r.save({...a,id:'test-2',parentId:a.id,solution:{...a.solution,entities:'Changed'}});assert.equal(r.list().length,2);assert.equal(r.list()[1].solution.entities,a.solution.entities);});
test('storage failures propagate instead of reporting false success',()=>{const r=new BrowserAttemptRepository({getItem:()=>null,setItem:()=>{throw new Error('Quota exceeded');}});assert.throws(()=>new EvaluationService(new RubricEvaluator(),r).run(attempt(),problems[0]),/Quota/);});
test('malformed history is not silently overwritten',()=>{const r=new BrowserAttemptRepository({getItem:()=>'{broken',setItem:()=>{throw new Error('Must not write');}});assert.throws(()=>r.list());});

test('verbose generic text does not earn requirement evidence',()=>{const generic='This is a very good design that is reliable and scalable and follows all the best practices. '.repeat(10);const r=new RubricEvaluator().evaluate(problems[0],{entities:generic,relationships:generic,flow:generic,edges:generic,code:''});assert.equal(r.documented,0);});
test('specific concise checkout explanation earns evidence',()=>{const r=new RubricEvaluator().evaluate(problems[0],{...problems[0].example,flow:'On successful checkout, release the spot.'});assert.equal(r.findings.find(f=>f.ruleId==='release')?.status,'evidence');});
test('omitted duplicate checkout produces actionable missing feedback',()=>{const r=new RubricEvaluator().evaluate(problems[0],{...problems[0].example,edges:'Reject unknown IDs. If full, return an error.'});assert.equal(r.findings.find(f=>f.ruleId==='duplicate')?.status,'missing');});
test('unsafe elevator movement is prioritised',()=>{const r=new RubricEvaluator().evaluate(problems[2],{...problems[2].example,flow:'The elevator moves while doors are open.'});assert.equal(r.findings[0].status,'risk');assert.match(r.nextSteps[0],/unsafe movement/);});
test('negated unsafe movement is not a risk',()=>{const r=new RubricEvaluator().evaluate(problems[2],problems[2].example);assert.ok(!r.findings.some(f=>f.status==='risk'));});
test('explicitly skipped implementation is not supporting evidence',()=>{const r=new RubricEvaluator().evaluate(problems[0],{...problems[0].example,flow:'We will not release the spot on successful checkout.',entities:'Objects hold state for this example.',relationships:'Components collaborate in a simple design.',edges:'Failures are returned to the calling user.'});assert.equal(r.findings.find(f=>f.ruleId==='release')?.status,'missing');});

test('revision comparison names newly supported behaviour',()=>{const e=new RubricEvaluator();const before=e.evaluate(problems[0],{...problems[0].example,flow:'The service does everything needed for parking.'});const after=e.evaluate(problems[0],problems[0].example);assert.ok(compareReports(before,after)?.added.includes('Checkout releases the spot'));assert.equal(compareReports({...before,version:'1.0'},after),null);});
