import { commonRules, problemRules } from './review-rules.ts';
export type Section = 'entities' | 'relationships' | 'flow' | 'edges';
export type Solution = Record<Section,string> & { code: string };
export type Problem = {id:string; title:string; level:string; minutes:number; description:string; tags:string[]; requirements:string[]; constraints:string[]; prompts:Record<Section,string>; example:Solution};
export const sections: {key:Section; title:string; description:string}[] = [
{key:'entities',title:'Classes & responsibilities',description:'Name the objects in your system and give each a clear job.'},
{key:'relationships',title:'Relationships & interfaces',description:'Explain how objects collaborate and where behaviour can vary.'},
{key:'flow',title:'Core behaviour',description:'Walk through the main operation, from request to result.'},
{key:'edges',title:'Edge cases & trade-offs',description:'Describe failures, boundaries, and the choices you made.'}];
export const emptySolution = ():Solution => ({entities:'',relationships:'',flow:'',edges:'',code:''});
export const problems:Problem[] = [
{id:'parking-lot',title:'Parking Lot',level:'Beginner',minutes:35,description:'Design a parking lot that assigns compatible spaces, issues tickets, and handles checkout. Keep responsibilities clear as pricing rules evolve.',tags:['Object modelling','Strategy pattern'],requirements:['Support motorcycles and cars with compatible parking spots.','Assign one available spot on entry and issue a unique ticket.','Calculate a parking fee on exit using duration and vehicle type.','Release the spot after successful checkout.','Handle a full lot, unknown tickets, and duplicate checkout.'],constraints:['Single parking lot; multiple floors are optional.','No real payments or external services are needed.','Choose and state your rounding and minimum-fee policy.'],prompts:{entities:'e.g. ParkingSpot owns availability; Ticket records entry time and the assigned spot…',relationships:'e.g. ParkingService depends on a PricingPolicy interface…',flow:'A car arrives → find a compatible available spot → reserve it → issue a ticket…',edges:'What happens when two cars request the last spot? How do you prevent double checkout?'},example:{entities:'Vehicle stores its registration and type. ParkingSpot owns its type and occupied state. Ticket stores a unique ID, vehicle, spot, entry time, and checkout status. ParkingService coordinates entry and exit. PricingPolicy computes a fee.',relationships:'ParkingService uses a SpotRepository and a TicketRepository. Ticket references one Vehicle and one ParkingSpot. HourlyPricing implements PricingPolicy; ParkingService receives that interface through its constructor.',flow:'On entry, ParkingService atomically finds and reserves a compatible spot, then saves a unique active ticket. On exit it loads the ticket, checks active status, computes the fee from elapsed time and vehicle type, marks the ticket closed, and releases the spot in one transaction.',edges:'If full, return NoSpotAvailable without creating a ticket. Reject unknown IDs. Return the original checkout result for a duplicate request. Use a transaction to prevent simultaneous allocation. Round up to the next hour, with a one-hour minimum. Assume no payment gateway.',code:''}},
{id:'vending-machine',title:'Vending Machine',level:'Intermediate',minutes:45,description:'Model a vending machine that accepts money, dispenses products, and safely returns change when an operation cannot finish.',tags:['State pattern','Encapsulation'],requirements:['Display products with prices and stock counts.','Accept money and track the current transaction balance.','Dispense a selected product only when funds and stock are sufficient.','Return correct change and support cancellation.','Handle out-of-stock products, insufficient funds, and unavailable change.'],constraints:['One active customer transaction at a time.','Use integer currency units, never floating point.','Hardware can be represented through interfaces.'],prompts:{entities:'Which object owns inventory? Who owns the transaction balance?',relationships:'How do dispensing, inventory, and payment collaborate?',flow:'Walk through insert money → select product → dispense → return change.',edges:'What happens if dispensing fails or exact change is unavailable?'},example:{entities:'Product stores ID and price. Inventory owns stock. Transaction owns inserted balance. ChangeDispenser owns coin counts. VendingMachine coordinates the interaction.',relationships:'VendingMachine uses Inventory, a Dispenser interface, and ChangeDispenser. Its state controls which commands are allowed.',flow:'Accept money into the active transaction. Validate stock and balance for selection. Reserve a product and available change before dispensing. On success decrement stock, return change, and close the transaction.',edges:'Reject an unavailable product without consuming balance. Allow cancellation with a refund. Reserve change before dispensing; if unavailable, ask for exact payment. On dispenser failure restore reservations and refund. Money uses integer units.',code:''}},
{id:'elevator',title:'Elevator System',level:'Intermediate',minutes:50,description:'Design a small building’s elevator controller. Coordinate floor requests, movement, and door safety without coupling scheduling to the elevator.',tags:['State modelling','Scheduling'],requirements:['Accept external floor requests and internal destination requests.','Track current floor, direction, and door state.','Schedule pending requests and move between valid floors.','Open doors at the destination; never move with doors open.','Handle duplicate requests, invalid floors, and emergency stops.'],constraints:['Start with a single elevator and ten floors.','Simulate movement; no real hardware or timing required.','Explain how you could replace the scheduling algorithm.'],prompts:{entities:'Who owns door state, current floor, and pending requests?',relationships:'How will a controller depend on a replaceable scheduling policy?',flow:'Walk through a request, scheduling, movement, arrival, and door opening.',edges:'What happens on an emergency stop or a request outside the floor range?'},example:{entities:'Elevator owns current floor, direction, and operating state. Door owns open/closed state. Request stores destination. Controller coordinates commands. SchedulingPolicy chooses the next stop.',relationships:'Controller depends on SchedulingPolicy and an Elevator interface. Elevator owns a Door and enforces the closed-door invariant before movement.',flow:'Validate the requested floor, deduplicate pending requests, and ask the scheduler for the next stop. Close doors, verify safe state, move one floor at a time, stop at the destination, remove its request, and open doors.',edges:'Reject floors outside 0–9. Deduplicate requests. Emergency stop prevents movement until an explicit reset; preserve pending requests. Never move with doors open. Start with FIFO scheduling behind a replaceable interface.',code:''}}
];
export type Finding = {section:Section; title:string; evidence:string; guidance:string; status:'documented'|'expand'|'evidence'|'missing'|'risk'; ruleId?:string; priority?:number};
export type Report = {mode:'rubric'|'heuristic'; version?:string; summary:string; findings:Finding[]; nextSteps:string[]; documented:number};
export interface DesignEvaluator { evaluate(problem:Problem,solution:Solution):Report; }
export class SubmissionValidator {
 validate(solution:Solution) { for(const s of sections) { if(typeof solution[s.key] !== 'string' || solution[s.key].trim().length < 30) throw new Error(`Add at least 30 characters to ${s.title.toLowerCase()}.`); if(solution[s.key].length > 12000) throw new Error(`${s.title} must be under 12,000 characters.`); } if(solution.code.length>20000) throw new Error('Code must be under 20,000 characters.'); }
}
// Sentence-level evidence is a signal for review, never proof of correctness.
export class RubricEvaluator implements DesignEvaluator {
 evaluate(problem:Problem,solution:Solution):Report {
 const rules=[...commonRules,...(problemRules[problem.id]??[])];
 if(!problemRules[problem.id]) throw new Error('No review rubric exists for this problem.');
 const passages=sections.flatMap(s=>solution[s.key].split(/(?<=[.!?])\s+|\n+/).map(text=>({section:s.key,text:text.trim()}))).filter(p=>p.text.length>15);
 const findings:Finding[]=rules.map(rule=>{
 const passage=passages.find(p=>rule.patterns.every(pattern=>pattern.test(p.text)) && !/\b(todo|not implemented|ignore|skip|won't|will not|do not|don't)\b/i.test(p.text) && p.text.split(/\s+/).length>=5);
 return {ruleId:rule.id,section:passage?.section??rule.section,title:rule.title,evidence:passage?.text??'',status:passage?'evidence':'missing',priority:rule.priority,guidance:passage?'Supporting wording found; verify the actual invariant and state changes. '+rule.guidance:'No clear supporting passage found. '+rule.guidance};
 });
 const risks=[{pattern:/\b(move|moving|moves)\b.{0,35}\b(?:with|while)\b.{0,15}doors? (?:are )?open/i,problem:'elevator',title:'Possible unsafe movement',guidance:'Movement must be blocked while doors are open. Put the guard in the object that controls movement.'},{pattern:/\b(float|double|floating.point)\b/i,problem:'vending-machine',title:'Possible currency precision risk',guidance:'Use integer minor units for money so comparisons and change calculations remain exact.'}];
 for(const risk of risks.filter(r=>r.problem===problem.id)){const passage=passages.find(p=>risk.pattern.test(p.text)&&!/\b(never|not|avoid|no|reject|prevent|cannot|don.t)\b/i.test(p.text));if(passage)findings.unshift({ruleId:'risk-'+risk.problem,section:passage.section,title:risk.title,evidence:passage.text,status:'risk',priority:0,guidance:risk.guidance});}
 const ordered=[...findings].sort((a,b)=>(a.status==='risk'?0:a.status==='missing'?1:2)-(b.status==='risk'?0:b.status==='missing'?1:2)||(a.priority??3)-(b.priority??3));
 return {mode:'heuristic',version:'2.0',summary:'This review looks for requirement-specific evidence and potential risks in your explanation. Missing evidence means the behaviour needs clarification, not that it is necessarily absent. Matching text does not verify correctness; no AI model was used.',findings,documented:findings.filter(f=>f.status==='evidence').length,nextSteps:ordered.slice(0,3).map(f=>f.title+': '+f.guidance)};
 }
}
export function compareReports(previous:Report,current:Report){
 if(previous.version!==current.version)return null;
 const before=new Map(previous.findings.map(f=>[f.ruleId,f.status]));
 return {added:current.findings.filter(f=>f.ruleId&&f.status==='evidence'&&before.get(f.ruleId)==='missing').map(f=>f.title),lost:current.findings.filter(f=>f.ruleId&&f.status==='missing'&&before.get(f.ruleId)==='evidence').map(f=>f.title)};
}
export type Attempt={id:string;problemId:string;createdAt:string;solution:Solution;status:'queued'|'evaluating'|'completed'|'failed';report?:Report;error?:string;parentId?:string};
export interface AttemptRepository { list():Attempt[]; save(attempt:Attempt):void; }
export class BrowserAttemptRepository implements AttemptRepository {
 constructor(private storage:Pick<Storage,'getItem'|'setItem'>){}
 list():Attempt[] { const raw=this.storage.getItem('designlab.attempts.v1'); if(!raw)return []; const parsed=JSON.parse(raw); if(!Array.isArray(parsed))throw new Error('Saved history could not be read.');return parsed; }
 save(attempt:Attempt) {const all=this.list();const i=all.findIndex(a=>a.id===attempt.id);if(i<0)all.unshift(attempt);else all[i]=attempt;this.storage.setItem('designlab.attempts.v1',JSON.stringify(all));}
}
export class EvaluationService {
 constructor(private evaluator:DesignEvaluator,private repository:AttemptRepository){}
 run(attempt:Attempt,problem:Problem):Attempt {
 this.repository.save({...attempt,status:'evaluating'});
 let result:Attempt;
 try {new SubmissionValidator().validate(attempt.solution);result={...attempt,status:'completed',report:this.evaluator.evaluate(problem,attempt.solution),error:undefined};}
 catch(error){result={...attempt,status:'failed',error:error instanceof Error?error.message:'Evaluation failed. Your solution is preserved.'};}
 this.repository.save(result);return result;
 }
}
